[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.zip", "php82Extensions.bcmath", "php82Extensions.curl", "python3", "frankenphp"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan config:clear", "php artisan route:clear", "php artisan migrate --force", "php artisan db:seed --class=CtfChallengeSeeder --force", "chmod +x start.sh"]

[start]
cmd = "./start.sh"